PINK = "#e2979c"
RED = "#e7305b"
GREEN = "#9bdeac"
YELLOW = "#f7f5dd"

MIN_TO_SECONDS_CONVERTOR = 60

WORK_MIN = 25
SHORT_BREAK_MIN = 5
LONG_BREAK_MIN = 20

CANVAS_WIDTH = 204
CANVAS_HEIGHT = 224
CANVAS_X_POSITION = CANVAS_WIDTH // 2
CANVAS_Y_POSITION = CANVAS_HEIGHT // 2
CANVAS_TOMATO_IMAGE_FILE = "tomato.png"
CANVAS_PADDING_X = 100
CANVAS_PADDING_Y = 50

CANVAS_TEXT_X_POSITION = CANVAS_X_POSITION
CANVAS_TEXT_Y_POSITION = CANVAS_Y_POSITION + 25
CANVAS_TEXT_FILL_COLOR = "white"
CANVAS_TEXT_FONT_TYPE = ("Courier", 26, "bold")

CHECK_MARK_TEXT = "✔"
CHECK_MARK_TEXT_COLOR = GREEN
CHECK_MARK_FONT_TYPE = ("Courier", 16, "normal")

TIMER_TEXT_FONT_TYPE = ("Courier", 56, "normal")
TIMER_TEXT_COLOR = GREEN
